'use server'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { createServiceClient } from '@/lib/supabase/service'
import { requirePortalRole } from '@/modules/rbac/guards'
import type { ActionResult } from '@/types/app'

const schema = z.object({ title: z.string().trim().min(2).max(160), description: z.string().trim().max(800).optional().or(z.literal('')), youtube_url: z.string().url(), thumbnail_url: z.string().url() })
function youtubeId(value: string) { try { const u = new URL(value); const host = u.hostname.replace(/^www\./, ''); if (host === 'youtu.be') return u.pathname.split('/').filter(Boolean)[0] ?? null; if (host !== 'youtube.com') return null; if (u.pathname === '/watch') return u.searchParams.get('v'); const p = u.pathname.split('/').filter(Boolean); return p[0] === 'shorts' || p[0] === 'embed' ? p[1] ?? null : null } catch { return null } }
async function studentId(userId: string) { const { data } = await createServiceClient().from('students').select('id').eq('user_id', userId).is('deleted_at', null).maybeSingle(); return (data as { id?: string } | null)?.id ?? null }
export async function createStudentVideo(_: unknown, formData: FormData): Promise<ActionResult<{ id: string }>> { const user = await requirePortalRole('student'); const parsed = schema.safeParse({ title: formData.get('title'), description: formData.get('description') || '', youtube_url: formData.get('youtube_url'), thumbnail_url: formData.get('thumbnail_url') }); if (!parsed.success) return { success:false, error:{ code:'VALIDATION', message:'Complete the title, YouTube link, and thumbnail.' } }; const id = youtubeId(parsed.data.youtube_url); if (!id) return { success:false,error:{code:'VALIDATION',message:'Use a YouTube or YouTube Shorts link.'} }; const sid = await studentId(user.id); if (!sid) return { success:false,error:{code:'NOT_FOUND',message:'Student record not found.'} }; const { data, error } = await createServiceClient().from('student_videos').insert({ student_id:sid, created_by:user.id, title:parsed.data.title, description:parsed.data.description || null, youtube_url:parsed.data.youtube_url, youtube_id:id, thumbnail_url:parsed.data.thumbnail_url }).select('id').single(); if (error || !data) return {success:false,error:{code:'DB_ERROR',message:error?.code === '23505' ? 'You already added this video.' : (error?.message ?? 'Could not save video.')}}; revalidatePath('/portal/student/videos'); return {success:true,data:{id:(data as {id:string}).id}} }
export async function deleteStudentVideo(id: string): Promise<ActionResult<void>> { const user=await requirePortalRole('student'); const sid=await studentId(user.id); if (!sid) return {success:false,error:{code:'NOT_FOUND',message:'Student record not found.'}}; const {error}=await createServiceClient().from('student_videos').delete().eq('id',id).eq('student_id',sid); if(error)return{success:false,error:{code:'DB_ERROR',message:error.message}}; revalidatePath('/portal/student/videos'); return{success:true,data:undefined} }
